USE InCycleClinique;
INSERT INTO Doctor (DoctorID, FirstName, LastName, Specialty) VALUES
(1, 'John', 'Doe', 'Cardiology'),
(2, 'Jane', 'Smith', 'Neurology'),
(3, 'Jim', 'Brown', 'Orthopedics'),
(4, 'Jake', 'White', 'Pediatrics'),
(5, 'Jill', 'Green', 'Dermatology'),
(6, 'Joe', 'Black', 'Oncology'),
(7, 'Jenny', 'Blue', 'Gastroenterology'),
(8, 'Jack', 'Yellow', 'Urology'),
(9, 'Julie', 'Purple', 'Ophthalmology'),
(10, 'Jason', 'Red', 'Psychiatry'),
(11, 'Jessica', 'Orange', 'Radiology'),
(12, 'Jordan', 'Pink', 'Anesthesiology'),
(13, 'Jasmine', 'Gray', 'Pathology'),
(14, 'Jerry', 'Brown', 'Surgery'),
(15, 'Janet', 'White', 'Emergency Medicine'),
(16, 'Jeff', 'Green', 'Family Medicine'),
(17, 'Joan', 'Black', 'Internal Medicine'),
(18, 'Jared', 'Blue', 'Nephrology'),
(19, 'Joy', 'Yellow', 'Obstetrics and Gynecology'),
(20, 'Javier', 'Purple', 'Otolaryngology'),
(21, 'Jocelyn', 'Red', 'Pediatrics'),
(22, 'Jorge', 'Orange', 'Physical Medicine and Rehabilitation'),
(23, 'Jade', 'Pink', 'Plastic Surgery'),
(24, 'Jasper', 'Gray', 'Preventive Medicine'),
(25, 'Janelle', 'Brown', 'Psychiatry'),
(26, 'Jonah', 'White', 'Pulmonology'),
(27, 'Jada', 'Green', 'Rheumatology'),
(28, 'Jaxon', 'Black', 'Sleep Medicine'),
(29, 'Jemma', 'Blue', 'Sports Medicine'),
(30, 'Jace', 'Yellow', 'Thoracic Surgery'),
(31, 'Jolene', 'Purple', 'Vascular Surgery'),
(32, 'Jett', 'Red', 'Allergy and Immunology'),
(33, 'Jillian', 'Orange', 'Critical Care Medicine'),
(34, 'Jude', 'Pink', 'Endocrinology'),
(35, 'Jocelyn', 'Gray', 'Geriatric Medicine'),
(36, 'Javier', 'Brown', 'Hematology'),
(37, 'Jada', 'White', 'Infectious Disease'),
(38, 'Jaxon', 'Green', 'Medical Genetics'),
(39, 'Jemma', 'Black', 'Neonatology'),
(40, 'Jace', 'Blue', 'Nuclear Medicine'),
(41, 'Jolene', 'Yellow', 'Pain Medicine'),
(42, 'Jett', 'Purple', 'Palliative Care'),
(43, 'Jillian', 'Red', 'Public Health'),
(44, 'Jude', 'Orange', 'Reproductive Endocrinology'),
(45, 'Jocelyn', 'Pink', 'Transplant Surgery'),
(46, 'Javier', 'Gray', 'Trauma Surgery'),
(47, 'Jada', 'Brown', 'Undersea and Hyperbaric Medicine'),
(48, 'Jaxon', 'White', 'Urgent Care Medicine'),
(49, 'Jemma', 'Green', 'Wound Care'),
(50, 'Jace', 'Black', 'General Practice');