/*
 * This source file was generated by the Gradle 'init' task
 */
package Incycle.Clinique;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    @Disabled("Skipping this test")
    void SampleTest() {
        assertEquals(11,6+6);
    }

    @Test
    void SampleTest2() {
        assertEquals(12,6+6);
    }

}
